const state={page:'home',robot:true,loading:true,error:null,data:null,offerPlans:null,offerBusy:null,checkoutResult:null};
const app=document.querySelector('#app');
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function selectedProducts(){return state.data?.products?.selected||[]}
function dashboard(){return state.data?.dashboard||{kpis:{salesToday:0,revenueToday:0,leadsToday:0,conversionRate:0},pipeline:{researched:0,selected:0}}}
function finance(){return state.data?.finance||{available:0,pending:0,paidToday:0,sandbox:true}}
function statusMessage(){if(state.loading)return '<div class="card"><p class="note">Carregando dados reais do NEXORA AI…</p></div>';if(state.error)return `<div class="card"><p class="note">Não foi possível carregar os dados do servidor. ${escapeHtml(state.error)}</p><button class="btn" id="retry">Tentar novamente</button></div>`;return ''}
function render(){const d=dashboard(),f=finance(),products=selectedProducts();app.innerHTML=`<div class="shell"><header class="top"><div class="brand"><div><h1>NEXORA AI</h1><small>Controle pelo celular</small></div><div class="avatar">🤖</div></div></header><main class="content">${statusMessage()}${pageHome(d,f,products)}${pageProducts(products)}${pageSales(d)}${pageFinance(f)}</main><nav class="nav"><div class="navin">${nav('home','⌂','Início')}${nav('products','⌁','Produtos')}${nav('sales','◫','Vendas')}${nav('finance','R$','Financeiro')}</div></nav></div>`;bind()}
function nav(p,i,t){return `<button class="${state.page===p?'active':''}" data-page="${p}"><span>${i}</span>${t}</button>`}
function pageHome(d,f,products){return `<section class="page ${state.page==='home'?'active':''}"><div class="hero"><h2>Seu robô está trabalhando.</h2><p>Este painel exibe somente dados recebidos da API do NEXORA AI. Nenhum número de demonstração é usado.</p><div class="status"><i class="dot"></i> Robô ${state.robot?'ativo':'pausado'}</div><div class="actions"><button class="btn" id="toggle">${state.robot?'Pausar robô':'Ativar robô'}</button><button class="btn secondary" data-page="products">Ver oportunidades</button></div></div><div class="grid"><div class="card"><div class="label">Vendas hoje</div><div class="value">${d.kpis.salesToday}</div></div><div class="card"><div class="label">Faturamento hoje</div><div class="value positive">${money(d.kpis.revenueToday)}</div></div><div class="card"><div class="label">A receber</div><div class="value">${money(f.pending)}</div></div><div class="card"><div class="label">Modo</div><div class="value">${state.data?'Autônomo':'—'}</div></div></div><div class="section"><h3>Melhores oportunidades</h3><span class="link">Dados da API</span></div><div class="card list">${products.length?products.map(p=>`<div class="op"><div><div class="name">${escapeHtml(p.name)}</div><div class="sub">${escapeHtml(p.category)} · margem ${(Number(p.margin||0)*100).toFixed(0)}%</div></div><div class="score">${Number(p.score||0)}</div></div>`).join(''):'<p class="note">Nenhuma oportunidade elegível no momento.</p>'}</div></section>`}
function offerCard(product,plan){const busy=state.offerBusy===product.id;const result=state.checkoutResult?.productId===product.id?state.checkoutResult:null;return `<div class="card offer-card"><div class="section"><h3>💰 ${escapeHtml(plan.offer.name)}</h3><span class="pill">${escapeHtml(plan.offer.checkout)}</span></div><p class="note">${escapeHtml(plan.offer.headline)}</p><div class="row"><span>Preço</span><strong>${money(plan.offer.price)}</strong></div><div class="row"><span>Score / margem</span><span>${plan.offer.evidence.score} / ${(plan.offer.evidence.margin*100).toFixed(0)}%</span></div><form class="offer-form" data-product-id="${escapeHtml(product.id)}"><input name="name" placeholder="Nome do cliente" autocomplete="name"><input name="email" type="email" placeholder="E-mail do cliente" autocomplete="email" required><button class="btn" ${busy?'disabled':''}>${busy?'Criando checkout…':'Criar checkout sandbox'}</button></form>${result?`<div class="card"><p class="note">Checkout criado em <strong>Sandbox</strong>. ID do pedido: ${escapeHtml(result.order?.id||'—')}</p><p class="note">Pagamento: ${escapeHtml(result.payment?.status||'pending')}. Nenhuma cobrança real foi realizada.</p></div>`:''}</div>`}
function pageProducts(products){const plans=state.offerPlans||[];return `<section class="page ${state.page==='products'?'active':''}><div class="section"><h3>Inteligência Comercial</h3><span class="pill">${products.length} selecionados</span></div><p class="note">As oportunidades abaixo vêm diretamente da API e obedecem à política de autonomia do servidor.</p><div class="list">${products.length?products.map(p=>`<div class="card"><div class="row"><div><div class="name">${escapeHtml(p.name)}</div><div class="sub">${escapeHtml(p.category)} · Product Opportunity Score</div></div><div class="score">${Number(p.score||0)}</div></div><div class="actions"><button class="btn" data-offer-id="${escapeHtml(p.id)}">${plans.some(x=>x.opportunity.id===p.id)?'Oferta pronta':'Preparar oferta'}</button><button class="btn secondary">Detalhes</button></div></div>`).join(''):'<div class="card"><p class="note">Nenhum produto selecionado pela política atual.</p></div>'}</div>${plans.length?`<div class="section"><h3>Ofertas verificadas</h3><span class="pill">${plans.length}</span></div><div class="list">${plans.map(plan=>offerCard(plan.opportunity,plan)).join('')}</div>`:''}</section>`}
function pageSales(d){const rate=(Number(d.kpis.conversionRate||0)*100).toFixed(1).replace('.',',');return `<section class="page ${state.page==='sales'?'active':''}><div class="section"><h3>Vendas e Funil</h3><span class="pill">Dados atuais</span></div><div class="grid"><div class="card"><div class="label">Leads</div><div class="value">${d.kpis.leadsToday}</div></div><div class="card"><div class="label">Negociação</div><div class="value">—</div></div><div class="card"><div class="label">Checkout</div><div class="value">—</div></div><div class="card"><div class="label">Conversão</div><div class="value positive">${rate}%</div></div></div><div class="section"><h3>Automação</h3></div><div class="card"><div class="toggle"><div><div class="name">Follow-up automático</div><div class="sub">Regras de follow-up serão exibidas quando o funil tiver dados reais.</div></div><span class="pill">API</span></div><hr style="border:0;border-top:1px solid #20283e;margin:16px 0"><div class="toggle"><div><div class="name">Modo de aprovação</div><div class="sub">Decisões importantes passam por você</div></div><span class="pill">Assistido</span></div></div></section>`}
function pageFinance(f){return `<section class="page ${state.page==='finance'?'active':''}><div class="section"><h3>Financeiro</h3><span class="pill">${f.sandbox?'Sandbox':'Produção'}</span></div><div class="card"><div class="label">Disponível</div><div class="value positive">${money(f.available)}</div><div class="label" style="margin-top:14px">Pendente</div><div class="value">${money(f.pending)}</div><p class="note">Valores carregados da API. O gateway continua em sandbox até a validação do fluxo de pagamento real.</p></div><div class="section"><h3>Fluxo financeiro</h3></div><div class="card list"><div class="row"><span>Pagamentos confirmados hoje</span><span class="pill">${money(f.paidToday)}</span></div><div class="row"><span>Liquidação pendente</span><span class="pill">${money(f.pending)}</span></div><div class="row"><span>Repasse bancário</span><span class="pill">protegido</span></div></div></section>`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});const t=document.querySelector('#toggle');if(t)t.onclick=()=>{state.robot=!state.robot;render()};const retry=document.querySelector('#retry');if(retry)retry.onclick=loadData;document.querySelectorAll('[data-offer-id]').forEach(b=>b.onclick=async()=>{try{state.offerPlans=await RoboAPI.commercialPlan();render()}catch(e){alert(e.message||'Não foi possível preparar as ofertas.')}});document.querySelectorAll('.offer-form').forEach(form=>form.onsubmit=async(e)=>{e.preventDefault();const productId=form.dataset.productId;const data=new FormData(form);state.offerBusy=productId;state.checkoutResult=null;render();try{const r=await RoboAPI.checkout({productId,customer:{name:data.get('name'),email:data.get('email')},idempotencyKey:`web-${productId}-${Date.now()}`});state.checkoutResult={productId,...r};}catch(err){alert(err.message||'Não foi possível criar o checkout.')}finally{state.offerBusy=null;render()}})}
async function loadData(){state.loading=true;state.error=null;render();try{const [dashboard,products,finance]=await Promise.all([RoboAPI.dashboard(),RoboAPI.products(),RoboAPI.finance()]);state.data={dashboard,products,finance};}catch(e){state.error=e?.message||'Erro de comunicação com a API.';state.data=null;}finally{state.loading=false;render()}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();loadData();
async function setupNotifications(){const statusEl=document.querySelector('#push-status'),enable=document.querySelector('#enable-push'),test=document.querySelector('#test-push');if(!window.NotificationCenter)return;async function refresh(){const s=await NotificationCenter.status();if(statusEl)statusEl.textContent=s.subscription?'ativo':(s.permission==='denied'?'bloqueado':'desativado')}enable?.addEventListener('click',async()=>{const r=await NotificationCenter.subscribe();if(r.enabled){statusEl.textContent='ativo';alert('Notificações ativadas.')}else if(r.reason==='vapid-not-configured'){alert('A interface está pronta. O envio remoto será ativado quando a chave segura do servidor for configurada.')}else{alert('Não foi possível ativar as notificações neste dispositivo.')}await refresh()});test?.addEventListener('click',async()=>{try{await NotificationCenter.demoSale()}catch(e){alert(e.message||'Não foi possível testar.')}});refresh()}
setupNotifications();
