const state={page:'home',robot:true};
const data={ops:[['Organizador doméstico multifuncional',87,'Demanda alta · margem estimada alta'],['Acessório para celular',79,'Demanda alta · competição média'],['Kit de organização pessoal',72,'Demanda média · boa conversão']],sales:12,revenue:1840.50,pending:642.30};
const app=document.querySelector('#app');
function money(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function render(){app.innerHTML=`<div class="shell"><header class="top"><div class="brand"><div><h1>Robo Vendas AI</h1><small>Controle pelo celular</small></div><div class="avatar">🤖</div></div></header><main class="content">${pageHome()}${pageProducts()}${pageSales()}${pageFinance()}</main><nav class="nav"><div class="navin">${nav('home','⌂','Início')}${nav('products','⌁','Produtos')}${nav('sales','◫','Vendas')}${nav('finance','R$','Financeiro')}</div></nav></div>`;bind()}
function nav(p,i,t){return `<button class="${state.page===p?'active':''}" data-page="${p}"><span>${i}</span>${t}</button>`}
function pageHome(){return `<section class="page ${state.page==='home'?'active':''}"><div class="hero"><h2>Seu robô está trabalhando.</h2><p>O painel está preparado para acompanhar oportunidades, vendas e financeiro em uma única tela.</p><div class="status"><i class="dot"></i> Robô ${state.robot?'ativo':'pausado'}</div><div class="actions"><button class="btn" id="toggle">${state.robot?'Pausar robô':'Ativar robô'}</button><button class="btn secondary" data-page="products">Ver oportunidades</button></div></div><div class="grid"><div class="card"><div class="label">Vendas</div><div class="value">${data.sales}</div></div><div class="card"><div class="label">Faturamento</div><div class="value positive">${money(data.revenue)}</div></div><div class="card"><div class="label">A receber</div><div class="value">${money(data.pending)}</div></div><div class="card"><div class="label">Modo</div><div class="value">Assistido</div></div></div><div class="section"><h3>Melhores oportunidades</h3><span class="link">Score 0–100</span></div><div class="card list">${data.ops.map(o=>`<div class="op"><div><div class="name">${o[0]}</div><div class="sub">${o[2]}</div></div><div class="score">${o[1]}</div></div>`).join('')}</div></section>`}
function pageProducts(){return `<section class="page ${state.page==='products'?'active':''}"><div class="section"><h3>Inteligência Comercial</h3><span class="pill">3 candidatos</span></div><p class="note">O robô prioriza demanda, aceitação, conversão, economia, concorrência e risco. Estes dados são demonstrativos até conectarmos fontes reais.</p><div class="list">${data.ops.map((o,i)=>`<div class="card"><div class="row"><div><div class="name">${o[0]}</div><div class="sub">Product Opportunity Score</div></div><div class="score">${o[1]}</div></div><div class="actions"><button class="btn">${i===0?'Testar produto':'Selecionar'}</button><button class="btn secondary">Detalhes</button></div></div>`).join('')}</div></section>`}
function pageSales(){return `<section class="page ${state.page==='sales'?'active':''}"><div class="section"><h3>Vendas e Funil</h3><span class="pill">24h</span></div><div class="grid"><div class="card"><div class="label">Leads</div><div class="value">148</div></div><div class="card"><div class="label">Negociação</div><div class="value">31</div></div><div class="card"><div class="label">Checkout</div><div class="value">18</div></div><div class="card"><div class="label">Conversão</div><div class="value positive">8,1%</div></div></div><div class="section"><h3>Automação</h3></div><div class="card"><div class="toggle"><div><div class="name">Follow-up automático</div><div class="sub">Recontatar leads conforme regras do funil</div></div><div class="switch on"><i></i></div></div><hr style="border:0;border-top:1px solid #20283e;margin:16px 0"><div class="toggle"><div><div class="name">Modo de aprovação</div><div class="sub">Decisões importantes passam por você</div></div><span class="pill">Assistido</span></div></div></section>`}
function pageFinance(){return `<section class="page ${state.page==='finance'?'active':''}"><div class="section"><h3>Financeiro</h3><span class="pill">Sandbox</span></div><div class="card"><div class="label">Saldo demonstrativo</div><div class="value positive">${money(data.pending)}</div><p class="note">Quando conectarmos um gateway, pagamentos e repasses reais aparecerão aqui. Aprovação de pagamento não significa necessariamente disponibilidade bancária imediata.</p></div><div class="section"><h3>Fluxo financeiro</h3></div><div class="card list"><div class="row"><span>Pagamento</span><span class="pill">✓ confirmado</span></div><div class="row"><span>Liquidação</span><span class="pill">aguardando</span></div><div class="row"><span>Repasse bancário</span><span class="pill">protegido</span></div></div></section>`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});const t=document.querySelector('#toggle');if(t)t.onclick=()=>{state.robot=!state.robot;render()}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();

async function setupNotifications(){
  const statusEl=document.querySelector('#push-status'), enable=document.querySelector('#enable-push'), test=document.querySelector('#test-push');
  if(!window.NotificationCenter)return;
  async function refresh(){const s=await NotificationCenter.status(); statusEl.textContent=s.subscription?'ativo':(s.permission==='denied'?'bloqueado':'desativado');}
  enable?.addEventListener('click',async()=>{const r=await NotificationCenter.subscribe(); if(r.enabled){statusEl.textContent='ativo';alert('Notificações ativadas.');} else if(r.reason==='vapid-not-configured'){alert('A interface está pronta. O envio remoto será ativado quando a chave segura do servidor for configurada.');} else {alert('Não foi possível ativar as notificações neste dispositivo.');} await refresh();});
  test?.addEventListener('click',async()=>{try{await NotificationCenter.demoSale();}catch(e){alert(e.message||'Não foi possível testar.');}});
  refresh();
}
setupNotifications();
