import test from 'node:test'; import assert from 'node:assert/strict'; import worker from '../src/worker.js';
const post=(path,body)=>worker.fetch(new Request('https://nexora.test'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));
const get=path=>worker.fetch(new Request('https://nexora.test'+path));
async function create(amount){return (await (await post('/api/gateway/sandbox/create',{amount,idempotencyKey:crypto.randomUUID(),orderId:'order_e2e_'+crypto.randomUUID()})).json()).payment;}
async function signed(paymentId,status){return (await (await post('/api/gateway/sandbox/sign',{paymentId,status})).json());}

test('E2E sale -> ledger -> payout -> notification',async()=>{await post('/api/gateway/sandbox/reset',{});const p=await create(197);const s=await signed(p.id,'paid');const r=await (await post('/api/gateway/sandbox/webhook',{...s,idempotencyKey:'e2e-paid'})).json();assert.equal(r.ok,true);const pay=await (await post('/api/gateway/sandbox/payout',{paymentId:p.id})).json();assert.equal(pay.ok,true);const st=await (await get('/api/gateway/sandbox/state')).json();assert.equal(st.sales[0].status,'paid');assert.equal(st.ledger.filter(x=>x.type==='sale').length,1);assert.equal(st.ledger.filter(x=>x.type==='payout').length,1);assert.equal(st.notifications.filter(x=>x.type==='sale').length,1);});
test('refund reverses ledger and blocks payout',async()=>{await post('/api/gateway/sandbox/reset',{});const p=await create(99);const s=await signed(p.id,'paid');await post('/api/gateway/sandbox/webhook',{...s,idempotencyKey:'refund-paid'});const r=await (await post('/api/gateway/sandbox/refund',{paymentId:p.id,idempotencyKey:'refund-1'})).json();assert.equal(r.ok,true);const pay=await (await post('/api/gateway/sandbox/payout',{paymentId:p.id})).json();assert.equal(pay.ok,false);const st=await (await get('/api/gateway/sandbox/state')).json();assert.equal(st.sales[0].status,'refunded');assert.equal(st.ledger.filter(x=>x.type==='refund').length,1);});
test('chargeback reverses ledger',async()=>{await post('/api/gateway/sandbox/reset',{});const p=await create(120);const s=await signed(p.id,'paid');await post('/api/gateway/sandbox/webhook',{...s,idempotencyKey:'cb-paid'});const r=await (await post('/api/gateway/sandbox/chargeback',{paymentId:p.id,idempotencyKey:'cb-1'})).json();assert.equal(r.ok,true);const st=await (await get('/api/gateway/sandbox/state')).json();assert.equal(st.sales[0].status,'chargeback');assert.equal(st.ledger.filter(x=>x.type==='chargeback').length,1);});
test('duplicate payout is blocked',async()=>{await post('/api/gateway/sandbox/reset',{});const p=await create(80);const s=await signed(p.id,'paid');await post('/api/gateway/sandbox/webhook',{...s,idempotencyKey:'dup-payout'});assert.equal((await (await post('/api/gateway/sandbox/payout',{paymentId:p.id})).json()).ok,true);assert.equal((await (await post('/api/gateway/sandbox/payout',{paymentId:p.id})).json()).error,'PAYOUT_ALREADY_CREATED');});
