const SECRET='nexora-sandbox-secret-v1';
const payments=new Map(), events=new Set(), sales=new Map(), payouts=[], notifications=[], ledger=[];
function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function sign(payload){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload)));}
export async function createPayment({amount=0,shouldFail=false,idempotencyKey,orderId='ord_'+crypto.randomUUID()}){if(!idempotencyKey)throw new Error('IDEMPOTENCY_REQUIRED');const existing=[...payments.values()].find(p=>p.idempotencyKey===idempotencyKey);if(existing)return existing;const id='pay_'+crypto.randomUUID();const p={id,orderId,amount,status:'pending',shouldFail,idempotencyKey,createdAt:new Date().toISOString()};payments.set(id,p);return p;}
export async function webhook(paymentId,status){const payload=JSON.stringify({paymentId,status});return {payload,signature:await sign(payload)};}
export async function processWebhook(payload,signature,idempotencyKey){if(await sign(payload)!==signature)return{ok:false,status:401,error:'INVALID_SIGNATURE'};if(!idempotencyKey)return{ok:false,status:400,error:'IDEMPOTENCY_REQUIRED'};if(events.has(idempotencyKey))return{ok:true,status:200,duplicate:true};const {paymentId,status}=JSON.parse(payload),p=payments.get(paymentId);if(!p)return{ok:false,status:404,error:'PAYMENT_NOT_FOUND'};events.add(idempotencyKey);p.status=status;if(status==='paid'&&!sales.has(paymentId)){sales.set(paymentId,{paymentId,orderId:p.orderId,amount:p.amount,status:'paid'});ledger.push({type:'sale',paymentId,orderId:p.orderId,amount:p.amount});notifications.push({type:'sale',paymentId,orderId:p.orderId});}if(status==='refunded'&&sales.has(paymentId)){const sale=sales.get(paymentId);if(sale.status!=='refunded'){sale.status='refunded';ledger.push({type:'refund',paymentId,orderId:p.orderId,amount:-sale.amount});notifications.push({type:'refund',paymentId,orderId:p.orderId});}}if(status==='chargeback'&&sales.has(paymentId)){const sale=sales.get(paymentId);if(sale.status==='paid'){sale.status='chargeback';ledger.push({type:'chargeback',paymentId,orderId:p.orderId,amount:-sale.amount});notifications.push({type:'chargeback',paymentId,orderId:p.orderId});}}return{ok:true,status:200,duplicate:false,payment:p};}
export function payout(paymentId){const p=payments.get(paymentId);if(!p||p.status!=='paid'||sales.get(paymentId)?.status!=='paid')return{ok:false,error:'SETTLEMENT_NOT_AVAILABLE'};if(payouts.some(x=>x.paymentId===paymentId))return{ok:false,error:'PAYOUT_ALREADY_CREATED'};const x={id:'payout_'+crypto.randomUUID(),paymentId,amount:p.amount,status:'simulated'};payouts.push(x);ledger.push({type:'payout',paymentId,amount:-p.amount});return{ok:true,payout:x};}
export function snapshot(){return{payments:[...payments.values()],sales:[...sales.values()],payouts,notifications,ledger};}
export function reset(){payments.clear();events.clear();sales.clear();payouts.length=0;notifications.length=0;ledger.length=0;}
