function normalizePrice(value){
  if(value==null)return null;
  const s=String(value).replace(/R\\$|\\s/g,'').replace(/\\./g,'').replace(',','.');
  const n=Number(s); return Number.isFinite(n)?n:null;
}
function titleCase(text){return String(text||'').trim().replace(/\\s+/g,' ').replace(/(^|\\s)([a-záàâãéêíóôõúç])/gi,(m,p,c)=>p+c.toUpperCase());}
function inferCategory(name=''){const n=name.toLowerCase();if(/camis|calça|vestido|blusa|roupa|tênis|sapato/.test(n))return 'Moda';if(/celular|fone|carregador|cabo|eletrôn|smart|mouse|teclado/.test(n))return 'Eletrônicos';if(/maqui|shampoo|creme|perfume|batom|cosmét/.test(n))return 'Beleza';if(/casa|cozinha|panela|organizador|decoração|almofada/.test(n))return 'Casa';if(/curso|ebook|livro|aula|consultoria/.test(n))return 'Digital';return 'Geral';}
function buildDescription(name,category,price){const p=price!=null?' por R$ '+price.toFixed(2).replace('.',','):'';const templates={Moda:'Uma opção prática e versátil para o dia a dia, com foco em conforto e estilo.',Eletrônicos:'Uma solução prática para facilitar sua rotina, com uso simples e conveniente.',Beleza:'Uma opção pensada para complementar sua rotina de cuidados e beleza.',Casa:'Uma solução funcional para organizar, facilitar ou deixar sua casa mais prática.',Digital:'Conteúdo prático para ajudar você a aprender, aplicar e obter resultados.',Geral:'Uma opção prática para quem busca bom custo-benefício e facilidade de uso.'};return titleCase(name)+p+'. '+(templates[category]||templates.Geral);}
export function parseSmartCatalog(input=''){const text=String(input).replace(/\\r/g,'').trim();if(!text)return [];const lines=text.split(/\\n+/).map(x=>x.trim()).filter(Boolean);const out=[];for(const line of lines){const priceMatch=line.match(/(?:R\\$\\s*)?(\\d{1,3}(?:\\.\\d{3})*(?:,\\d{1,2})|\\d+(?:[.,]\\d{1,2}))/);const price=priceMatch?normalizePrice(priceMatch[1]):null;let name=line.replace(/(?:R\\$\\s*)?\\d{1,3}(?:\\.\\d{3})*(?:,\\d{1,2})|(?:R\\$\\s*)?\\d+(?:[.,]\\d{1,2})/,'').replace(/^[\\-•*|:]+|[\\-•*|:]+$/g,'').trim();if(!name)continue;const category=inferCategory(name);out.push({id:crypto.randomUUID(),name:titleCase(name),category,description:buildDescription(name,category,price),price,currency:'BRL',status:'draft',source:'nexora-smart-catalog'});}return out;}
export async function saveSmartProducts(env,products){if(!env?.DB)return products;for(const p of products){await env.DB.prepare('INSERT INTO smart_catalog_products (id,name,category,description,price,currency,status,source,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.name,p.category,p.description,p.price,p.currency,p.status,p.source,new Date().toISOString(),new Date().toISOString()).run();}return products;}
export async function loadSmartProducts(env){if(!env?.DB)return [];const r=await env.DB.prepare('SELECT id,name,category,description,price,currency,status,source,created_at AS createdAt,updated_at AS updatedAt FROM smart_catalog_products ORDER BY created_at DESC LIMIT 100').all();return r.results||[];}